modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="ic2cezmode"
version="${file.jarVersion}"
displayName="IC2C EZ Mode"
authors="YuRaNnNzZZ"
description='''
THE EZ Mode for IC2 Classic.
Changes to the mod gameplay:
- All wrenches have 100% drop rate
- Machines drop as if they were broken instead of explosing on overvoltage
- Crops are not destroyed when you run over them
'''

[[dependencies.ic2cezmode]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ic2cezmode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ic2cezmode]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.1,)"
    ordering="AFTER"
    side="BOTH"
